spring:
  application:
    name: demomybatis
  mvc:
    pathmatch:
      use-registered-suffix-pattern: true
#      use-suffix-pattern: true
server:
  port: 6060

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.mybatis.demomybatis.model



app:
  id: demomybatis-apollo

apollo:
  meta: http://10.23.141.112:9090
  bootstrap:
     enabled: true
  eagerLoad:
     enabled: true



logging:
  level:
    com:
     example:
      myabtis:
        demomyabtis: info
