package com.example.mybatis.demomybatis.generatormapper;

import com.example.mybatis.demomybatis.generatormodel.GeneratorCoffee;
import com.example.mybatis.demomybatis.generatormodel.GeneratorCoffeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface GeneratorCoffeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    long countByExample(GeneratorCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    int deleteByExample(GeneratorCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    @Delete({
        "delete from T_COFFEE",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    @Insert({
        "insert into T_COFFEE (NAME, CREATE_TIME, ",
        "UPDATE_TIME)",
        "values (#{name,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Long.class)
    int insert(GeneratorCoffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    int insertSelective(GeneratorCoffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    List<GeneratorCoffee> selectByExampleWithRowbounds(GeneratorCoffeeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    List<GeneratorCoffee> selectByExample(GeneratorCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    @Select({
        "select",
        "ID, NAME, CREATE_TIME, UPDATE_TIME",
        "from T_COFFEE",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.example.mybatis.demomybatis.generatormapper.GeneratorCoffeeMapper.BaseResultMap")
    GeneratorCoffee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") GeneratorCoffee record, @Param("example") GeneratorCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    int updateByExample(@Param("record") GeneratorCoffee record, @Param("example") GeneratorCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    int updateByPrimaryKeySelective(GeneratorCoffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COFFEE
     *
     * @mbg.generated Thu Dec 12 11:23:47 CST 2019
     */
    @Update({
        "update T_COFFEE",
        "set NAME = #{name,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GeneratorCoffee record);
}